config/routes.rb
Rails.application.routes.draw do

  root 'home#index'

  match 'home/snapshot'=> 'home#snapshot', via: [:post]
  resources :failovers
  resources :servers
  resources :addresses 

end

app/models/address.rb
class Address < ActiveRecord::Base
  belongs_to :failover

  def has_failed?
    failed_ping > 0 rescue false
  end

  def test
    rootUrl = self.address
    if rootUrl.include? "/"
      rootUrl = rootUrl.split('/')[0]
    end

    server_up = (`nmap #{rootUrl} -p #{port} -n | grep open | wc -l`.to_i > 0)
    website_up = true

    if(server_up && ([80, 443].include? self.port) )
      unless self.address.nil?
        address = self.address.include?("/") ? self.address :  self.address+"/"
        website_up = (`curl -silent -iL --max-time 10 #{address.sub("/",":#{port}/")} | head -n25 | egrep ' 200 OK| 302| 304' | wc -l`.to_i > 0)
      end
    end

    if(website_up && server_up)
      self.failed_ping = 0
      save!
    else
      self.failed_ping = self.failed_ping + 1
      save!

      #to catch this event, subscribe a listener object :
      #EventBus.subscribe(ErrorRecorder.new)
      #in which you implement a service_failed method :
      # def service_failed(payload)
      #   address = payload[:address]
      #   //...
      # end
      #for further information please see https://github.com/kevinrutherford/event_bus
      #a template exists in the initalizers folder
      EventBus.announce(:service_failed, address: self)
    end

  end

end

app/models/failover.rb
class Failover < ActiveRecord::Base
  belongs_to :master_server, :class_name => "Server", :foreign_key => "master_server_id"
  belongs_to :backup_server, :class_name => "Server", :foreign_key => "backup_server_id"
  has_many :addresses

  def has_failed?
    self.addresses.any? do |a|
      a.has_failed?
    end
  end

  def startable?
    !backup_server_id.nil? && state == 0
  end

  def stoppable?
    state == 1
  end

  def available_servers(as = :backup)
    if as == :backup
      Server.where('id != ?', (self.master_server_id.nil? ? -1 : self.master_server_id))
    else
      Server.where('id != ?', (self.backup_server_id.nil? ? -1 : self.backup_server_id))
    end
  end

  def start()
    response = ApiOnlineFailover.edit({source: self.ip, destination: self.backup_server.ip})
    if response[:status] == 200
      self.state = 1
      self.save!
      true
    else
      response[:json]["error"]
    end

  end

  def stop()
    response = ApiOnlineFailover.edit({source: self.ip, destination: self.master_server.ip})
    if response[:status] == 200
      self.state = 0
      self.save!
      true
    else
      response[:json]["error"]
    end
  end



  #Class methods
  def self.snapshot
    failovers = ApiOnlineFailover.all
    failovers.each do |f|

      Failover.where(ip: f["source"]).first_or_create(
        ip: f["source"],
        master_server_id: Server.find_by_ip(f["destination"]).id,
        state: 0
      )

    end
  end


end

app/models/server.rb
class Server < ActiveRecord::Base

  def startable?
    my_failovers.any?
  end

  def my_failovers
    Failover.where(master_server_id: id, state: 0).where('backup_server_id is not null')
  end

  def start()
    my_failovers.each do |f|
      f.start
    end
  end

  def stop()
    my_failovers.each do |f|
      f.stop
    end
  end

  #Class methods
  def self.snapshot
    servers = ApiOnlineServer.all
    servers.each do |s|
      tmp_id = Utils.extract_id(s)
      server_data = ApiOnlineServer.find_by_id(tmp_id)
      Server.where(online_id: tmp_id).first_or_create(
        online_id: tmp_id,
        ip: server_data["network"]["ip"].first,
        name:server_data["hostname"]
      )
    end
  end
end

app/controllers/addresses_controller.rb
class AddressesController < ApplicationController

  def create
    a = Address.new(address_params)
    a.failed_ping = 0
    a.save!
    redirect_to :back
  end

  def update
    a = Address.find(params[:id])
    a.update_attributes(address_params)
    a.failed_ping = 0
    a.save!
    redirect_to :back
  end

  def address_params
    params.require(:address).permit(:address, :port, :failover_id)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_filter :set_cache_buster

  require "#{Rails.root}/lib/api_online"
  require "#{Rails.root}/lib/api_online_server"
  require "#{Rails.root}/lib/api_online_failover"
  require "#{Rails.root}/lib/utils"


  def set_cache_buster
    response.headers["Cache-Control"] = "no-cache, no-store, max-age=0, must-revalidate"
    response.headers["Pragma"] = "no-cache"
    response.headers["Expires"] = "Fri, 01 Jan 1990 00:00:00 GMT"
  end
end

app/controllers/failovers_controller.rb
class FailoversController < ApplicationController

  def update
    unless params[:save].nil?
      f = Failover.find(params[:id])
      f.update_attributes(failover_params)
      f.save!
    end

    unless params[:start].nil?
      f = Failover.find(params[:id])
      response = f.start
      flash[:error] = response unless response==true
    end

    unless params[:stop].nil?
      f = Failover.find(params[:id])
      response = f.stop
      flash[:error] = response unless response==true
    end




    redirect_to :back
  end


  def failover_params
    params.require(:failover).permit(:state, :master_server_id, :backup_server_id, :name)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  def index
    @servers = Server.all
    @failovers = Failover.all
    @failovers.each{|f| f.addresses.build}
  end

  def snapshot
    Server.snapshot
    Failover.snapshot
    redirect_to :back
  end
end

app/controllers/servers_controller.rb
class ServersController < ApplicationController

  def update
    unless params[:save].nil?
      f = Server.find(params[:id])
      f.update_attributes(server_params)
      f.save!
    end

    unless params[:start].nil?
      f = Server.find(params[:id])
      f.start
    end

    unless params[:stop].nil?
      f = Server.find(params[:id])
      f.stop
    end




    redirect_to :back
  end


  def server_params
    params.require(:server).permit(:name)
  end
end

app/helpers/addresses_helper.rb
module AddressesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/failovers_helper.rb
module FailoversHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/index.html.haml
.row
  .col-lg-12
    %h2
      =t :servers
    -@servers.each do |server|
      .row
        = form_for server do |f|
          .col-lg-3
            = server.ip
          .col-lg-3
            = f.text_field :name, {placeholder: t('server.placeholder_name')}
          .col-lg-4
            = f.button t('server.save'), {class: "btn btn-primary", name:"save"}
            -if server.startable?
              = f.button t('server.start', host: server.name), {class: "btn btn-danger", name: "start"}



.row
  .col-lg-12
    %h2
      =t :failovers

    -@failovers.each do |failover|
      .failovers
        .row
          = form_for failover do |f|
            .col-lg-2
              %span.ip
                = failover.ip
              &#160;
              -if failover.has_failed?
                %span.label.label-warning
                  =t('failover.failed')
              -else
                %span.label.label-success
                  =t('failover.up')
            .col-lg-8
              = f.text_field :name, {placeholder: t('failover.placeholder_name')}
              /= f.text_field :state
              = f.select :master_server_id,
                failover.available_servers(:master).collect { |s| [ "#{s.name}-#{s.ip}", s.id ] },
                {},{disabled: failover.stoppable?}
              = f.select :backup_server_id,
                failover.available_servers(:backup).collect { |s| [ "#{s.name}-#{s.ip}", s.id ] },
                {include_blank: t('failover.placeholder_backup_server')},
                {disabled: failover.stoppable?}

            .col-lg-2
              = f.button t('server.save'), {class: "btn btn-primary", name: "save"}
              -if failover.startable?
                = f.button t('failover.start'), {class: "btn btn-danger", name: "start"}
              -if failover.stoppable?
                = f.button t('failover.stop'), {class: "btn btn-warning", name: "stop"}

        -failover.addresses.each do |a|
          .addresses
            = form_for a do |f|
              .row
                .col-lg-3
                  = f.text_field :address, {placeholder: t('address.placeholder_address', host: failover.ip)}
                  = f.text_field :port, {class: 'port', placeholder: t('address.placeholder_port')}
                  = f.hidden_field :failover_id, value: failover.id
                .col-lg-1
                  = f.button t('address.save'), {class: "btn btn-primary"}
                .col-lg-2
                  -if !a.id.nil?
                    -if a.has_failed?
                      %span.label.label-warning
                        =t('address.failed')
                    -else
                      %span.label.label-success
                        =t('address.up')



.row
  .col-lg-12
    %h2
      =t :data_sync
    .row
      .col-lg-2
        = form_tag home_snapshot_path, :method => "post" do
          = submit_tag t(:snapshot_button)

app/views/layouts/application.html.haml
!!! 5
%html(lang="en")
  %head
    %meta(charset="utf-8")
    %meta(http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1")
    %meta(name="viewport" content="width=device-width, initial-scale=1.0")
    %title= content_for?(:title) ? yield(:title) : "OnlineFailoverRails"
    = csrf_meta_tags
    / Le HTML5 shim, for IE6-8 support of HTML elements
    /[if lt IE 9]
      = javascript_include_tag "//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js"
    = stylesheet_link_tag "application", :media => "all"
    = favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144'
    = favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114'
    = favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72'
    = favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png'
    = favicon_link_tag 'favicon.ico', :rel => 'shortcut icon'
    = javascript_include_tag "application"


  %body
    .navbar.navbar-default.navbar-static-top
      .container
        %button.navbar-toggle(type="button" data-toggle="collapse" data-target=".navbar-responsive-collapse")
          %span.icon-bar
          %span.icon-bar
          %span.icon-bar
        %a.navbar-brand(href="#") Online Failover Rails
        .navbar-collapse.collapse.navbar-responsive-collapse
          %ul.nav.navbar-nav
            -#%li= link_to "Link 1", "/path1"
            -#%li= link_to "Link 2", "/path2"
            -#%li= link_to "Link 3", "/path3"
            -#%li= link_to "Link 3", "/path3"

    .container
      .row
        .col-lg-12
          = bootstrap_flash
          = yield

      %br
      %br
      %footer
        %p
          Jumboweb
          =Time.now.year